import { Runtime } from './lib/runtime.ts'
import { abs, join } from './lib/config.ts'

const CONFIG_CANDIDATES = ['config.yml', 'config.yaml']

// Written into the deployment root (cwd) when no config file exists there.
const DEFAULT_CONFIG =
  `# Default config generated by lonesome-lake on first boot.
# Paths resolve relative to this directory (the deployment root).

listen: "127.0.0.1:18080"
threads: 1
workStealing: false

workerTransport:
  kind: unix
  dir: "./data/sockets"
  prefix: "fn-"

loadBalancer:
  algorithm: round_robin

functionsDir: "./functions"

admin:
  listen: "127.0.0.1:19090"
  staticDir: "./static"
  token: ""
`

function parseConfigFlag(): string | null {
  const args = Deno.args
  const idx = args.indexOf('--config')
  if (idx >= 0 && args[idx + 1]) return args[idx + 1]
  return null
}

function findConfig(cwd: string): string | null {
  for (const name of CONFIG_CANDIDATES) {
    const p = join(cwd, name)
    try {
      Deno.statSync(p)
      return p
    } catch {
      // keep looking
    }
  }
  return null
}

function ensureDefaultConfig(cwd: string): string {
  const configPath = join(cwd, 'config.yml')
  Deno.writeTextFileSync(configPath, DEFAULT_CONFIG)
  console.log(`[config] no config found; generated default at ${configPath}`)
  try {
    Deno.mkdirSync(join(cwd, 'functions'), { recursive: true })
  } catch {
    // best-effort
  }
  return configPath
}

const cwd = Deno.cwd()
const explicit = parseConfigFlag()
const configPath = explicit
  ? abs(cwd, explicit)
  : findConfig(cwd) ?? ensureDefaultConfig(cwd)

const runtime = new Runtime({
  cwd,
  configPath,
})

let exiting = false
async function shutdown(): Promise<void> {
  if (exiting) return
  exiting = true
  await runtime.shutdown()
  Deno.exit(0)
}

Deno.addSignalListener('SIGINT', () => void shutdown())
Deno.addSignalListener('SIGTERM', () => void shutdown())

runtime.start()
await new Promise(() => {})
